cols <- c("dist_to_nearest_tree", "distance_to_nearest_tree", "dist_to_nearest_building", "distance_to_nearest_building", "angular_diff_tree", "num_trees_2m", "num_trees_5m", "num_trees_10m",  "area_tree_2m", "area_of_trees_2m", "area_tree_5m",  "area_tree_10m",  "area_of_trees_10m", "area_ext_tree10", "area_ext_build_2", "area_ext_build_10", "area_ext_build_25", "area_ext_build_50", "area_ext_build_100", "angular_diff_build", "build_dens", "tree_dens", "bl___10", "bl___25", "bl___50", "b___100", "dist_to_nearest_tree", "dist_to_building", "angular_diff_tree", "num_trees_2m", "num_trees_5m", "num_trees_10m", "area_ext_tree2",  "area_ext_tree_5", "area_ext_tree_10", "total_build_2m", "total_build_5m", "total_build_10m", "angular_diff_build", "BuildingKernelDensity_MEAN", "TreeKernelDensity_MEAN", "dist_to_nearest_tree", "dist_to_nearest_struc", "angular_diff_tree", "num_trees_2m", "num_trees_5m", "num_trees_10m",  "area_tree_2m",  "area_tree_5m",  "area_tree_10m", "area_ext_build_2", "area_ext_build_10", "area_ext_build_25", "area_ext_build_50", "area_ext_build_100", "angular_diff_build", "BuildingKernelDensity_MEAN", "TreeKernelDensity_MEAN", "bl___10", "bl___25", "bl___50", "b___100", "dist_to_nearest_tree", "angular_diff_tree", "num_trees_2m", "num_trees_5m",   "num_trees_10m", "total_build_2m", "total_build_5m", "total_build_10m", "area_ext_tree_2",  "area_ext_tree_5",  "area_ext_tree10", "dist_to_building", "angular_diff_build", "BuildingKernelDensity_MEAN", "TreeKernelDensity_MEAN", "dist_to_nearest_tree:angular_diff_tree", "distance_to_nearest_tree:angular_diff_tree", "dist_to_nearest_building:angular_diff_build", "distance_to_nearest_building:angular_diff_build",  'dist_to_nearest_struc:angular_diff_build', "build_dens:tree_dens", "mean_wind_sp",
          "distance_to_nearest_tree:angular_diff_tree:mean_wind_sp", "angular_diff_tree:mean_wind_sp", "distance_to_nearest_tree:mean_wind_sp", "mean_wind_sp:distance_to_nearest_building:angular_diff_build", "mean_wind_sp:distance_to_nearest_building", "mean_wind_sp:angular_diff_build", "total_build_200_m", "area_tree_200m", "fprint_area", "total_build_200_m:area_tree_200m", "mean_perc_struc", "mean_perc_tree", "num_builds_200m", "num_trees_200m", "tree_dens:build_dens")

cols_unique <- unique(cols)

human_labels <- c(
  "Distance to nearest tree (m)",
  "Distance to nearest tree (m)",
  "Distance to nearest structure (m)",
  "Distance to nearest structure (m)",
  "Degs. from downwind of tree",
  "Number of trees within 2 m",
  "Number of trees within 5 m",
  "Number of trees within 10 m",
  "Area of tree canopy within 2 m (m<sup>2</sup>)",
  "Area of tree canopy within 2 m (m<sup>2</sup>)",
  "Area of tree canopy within 5 m (m<sup>2</sup>)", 
  "Area of tree canopy within 10 m (m<sup>2</sup>)", 
  "Area of tree canopy within 10 m (m<sup>2</sup>)",
  "Area of tree canopy within 10 m (m<sup>2</sup>)",
  "Area of structure footprint within 2 m (m<sup>2</sup>)",
  "Area of structure footprint within 10 (m<sup>2</sup>)m",
  "Area of structure footprint within 25 (m<sup>2</sup>)m",
  "Area of structure footprint within 50 (m<sup>2</sup>)m",
  "Area of structure footprint within 100 m (m<sup>2</sup>)",
  "Degs. from downwind of structure",
  "Structure density (ha<sup>-1</sup>)",
  "Tree density (ha<sup>-1</sup>)",
  "Volume of structure within 10 m",
  "Volume of structure within 25 m",
  "Volume of structure within 50 m",
  "Volume of structure within 100 m",
  "Distance to nearest structure (m)",
  "Area of tree canopy within 2 m (m<sup>2</sup>)",
  "Area of tree canopy within 5 m (m<sup>2</sup>)",
  "Area of tree canopy within 10 m (m<sup>2</sup>)",
  "Area of structure footprint within 2 m (m<sup>2</sup>)",
  "Area of structure footprint within 5 m (m<sup>2</sup>)",
  "Area of structure footprint within 10 m (m<sup>2</sup>)",
  "Structure density (ha<sup>-1</sup>)",
  "Tree density (ha<sup>-1</sup>)",
  "Distance to nearest structure (m)",
  "Area of tree canopy within 2 m (m<sup>2</sup>)",
  "Distance to nearest tree:\nDegs. from downwind of tree",
  "Distance to nearest tree:\nDegs. from downwind of tree",
  "Distance to nearest structure:\nDegs. from downwind of structure",
  "Distance to nearest structure:\nDegs. from downwind of structure",
  "Distance to nearest structure:\nDegs. from downwind of structure",
  "Structure density: Tree density", 
  "Mean Wind Speed",
  "Distance to nearest tree:\nAngular difference from NE (tree):Wind Speed",
  "Angular difference from NE (tree):Wind Speed",
  "Distance to nearest tree:Wind Speed",
  "Distance to nearest build:\nAngular difference from NE (build):Wind Speed",
  "Distance to nearest build:Wind Speed",
  "Angular difference from NE (build):Wind Speed",
  "Area build footprint 200 m",
  "Area tree canoy 200 m",
  "Area of structure footprint",
  "Area build footprint 200 m : Area tree canoy 200 m",
  "Percent struc 200 m",
  "Percent tree 200 m",
  "Num builds 200 m",
  "Num trees 200 m",
  "Tree density: Structure density"
) 

label_map <- setNames(human_labels, cols_unique)
label_map
