---
title: "Explore_alt_models"
output: html_document
---

```{r}

library(dplyr)
library(gridExtra)
library(ggplot2)
library(cowplot)
library(tmap)
library(tmaptools)
library(sf)
library(terra)
library(grid)
library(corrplot)
library(reshape2)
library(spatialEco)
library(INLA)
library(sp)
library(spaMM)

source("functions/plot_alt_models.R")
source("functions/compare_AIC.R")
```


## Gen Eaton input

```{r}

## Eaton struc


eaton_wind <- read.csv("../wind_data/all_hrrr.csv") %>% 
  filter(point_fire == "eaton") %>% group_by(point_UID) %>% 
  summarize(mean_wind_sp = mean(wdsp), 
            mean_wind_dir = mean(wdir))

eaton_areas <- read.csv("../model_inputs/eaton_burned_alt_inputs.csv")


Eaton_struc <- read.csv("../model_inputs/eaton_burned_struc_model_inputs.csv") %>% 
  select(-X) %>% 
  filter(DAMAGE %in% c("Destroyed (>50%)", "No Damage", "Affected (1-9%)")) %>% 
  na.omit() %>% 
  left_join(eaton_wind, by = c("UID" = "point_UID")) %>% 
  left_join(eaton_areas, by = "UID")

Eaton_struc <- Eaton_struc %>% mutate(angular_diff_build = pmin(abs(bearing_to_nearest_building - mean_wind_dir), 360 - abs(bearing_to_nearest_building - mean_wind_dir)), angular_diff_tree = pmin(abs(bearing_to_nearest_tree - mean_wind_dir), 360 - abs(bearing_to_nearest_tree - mean_wind_dir)), destroyed = if_else(DAMAGE %in% c("No Damage", "Affected (1-9%)"),0,1)) %>% 
  rename(area_tree_200m = area_tree_200m.y, area_tree_100m = area_tree_200m.x)

cols <- c("distance_to_nearest_tree", "distance_to_nearest_building", "angular_diff_tree", "number_of_trees_2m", "number_of_trees_5m", "number_of_trees_10m",  "area_of_trees_2m",  "area_of_trees_5m",  "area_of_trees_10m", "area_ext_build_2", "area_ext_build_10", "area_ext_build_25", "area_ext_build_50", "area_ext_build_100", "angular_diff_build", "build_dens", "tree_dens", "mean_perc_struc", "area_tree_200m", "total_build_200_m", "fprint_area", "num_trees_200m", "mean_tree_density", "mean_struc_density", "num_builds_200m", "tree_dens_500", "tree_dens_1000", "area_tree_100m", "area_tree_50m", "total_build_100_m")

names(cols) <- cols

Eaton_struc_scale <- mutate(Eaton_struc, across(all_of(cols), ~ scale(.x, center = F)))

spd <- sp::SpatialPointsDataFrame(
  coords = Eaton_struc[, c("utm_x", "utm_y")],
  data = Eaton_struc)

bound <- inla.nonconvex.hull(spd, convex = -.01, resolution = c(105,82))

mesh <- inla.mesh.2d(boundary = bound, max.edge = 200)

# Create SPDE model
spde <- INLA::inla.spde2.matern(mesh)

spaMM.options(separation_max = 100) # or even higher if suggested


```


# Model with tree dens, struc dens

```{r}

eaton_struc_dens_scale <- fitme(destroyed ~ distance_to_nearest_tree * angular_diff_tree + area_of_trees_2m + 
                               area_ext_build_2 + distance_to_nearest_building + angular_diff_build +   mean_wind_sp + 
                               build_dens + tree_dens  + IMRF(1 | utm_x + utm_y, model = spde), data = Eaton_struc_scale)


eaton_struc_dense <- fitme(destroyed ~ distance_to_nearest_tree * angular_diff_tree + area_of_trees_2m + 
                         area_ext_build_2 + distance_to_nearest_building + angular_diff_build +   mean_wind_sp + 
                         build_dens + tree_dens  + IMRF(1 | utm_x + utm_y, model = spde), data = Eaton_struc)

```


# Plot model

```{r}

plot_alt_models(model = eaton_struc_dens_scale)


```

# Model with tree area, struc area 

```{r}

eaton_struc_area_scale <- fitme(destroyed ~ distance_to_nearest_tree * angular_diff_tree + area_of_trees_2m + 
                               area_ext_build_2 + distance_to_nearest_building + angular_diff_build +   mean_wind_sp + 
                               total_build_200_m + area_tree_200m + IMRF(1 | utm_x + utm_y, model = spde), data = Eaton_struc_scale)


eaton_struc_area <- fitme(destroyed ~ distance_to_nearest_tree * angular_diff_tree + area_of_trees_2m + 
                         area_ext_build_2 + distance_to_nearest_building + angular_diff_build +   mean_wind_sp + total_build_200_m + area_tree_200m + IMRF(1 | utm_x + utm_y, model = spde), data = Eaton_struc)

```


## Plot model

```{r}


plot_alt_models(eaton_struc_area_scale)
  


```

# Model with tree area 50, struc area 100

```{r}

eaton_struc_area50.100_scale <- fitme(destroyed ~ distance_to_nearest_tree * angular_diff_tree + area_of_trees_2m + 
                               area_ext_build_2 + distance_to_nearest_building + angular_diff_build +   mean_wind_sp + 
                               total_build_100_m + area_tree_50m + IMRF(1 | utm_x + utm_y, model = spde), data = Eaton_struc_scale)

```

```{r}


plot_alt_models(eaton_struc_area50.100_scale)

```

# Model with tree area 100, struc area 

```{r}

eaton_struc_area100_scale <- fitme(destroyed ~ distance_to_nearest_tree * angular_diff_tree + area_of_trees_2m + 
                               area_ext_build_2 + distance_to_nearest_building + angular_diff_build +   mean_wind_sp + 
                               build_dens + area_tree_100m + IMRF(1 | utm_x + utm_y, model = spde), data = Eaton_struc_scale)


```

# Plot

```{r}

plot_alt_models(eaton_struc_area100_scale)


```



# Model with tree area 50, struc area 

```{r}

eaton_struc_area50_scale <- fitme(destroyed ~ distance_to_nearest_tree * angular_diff_tree + area_of_trees_2m + 
                               area_ext_build_2 + distance_to_nearest_building + angular_diff_build +   mean_wind_sp + 
                               build_dens + area_tree_50m + IMRF(1 | utm_x + utm_y, model = spde), data = Eaton_struc_scale)


```

#Plot

```{r}

plot_alt_models(eaton_struc_area50_scale)


```




# Model with num trees, num builds

```{r}

eaton_struc_num200_scale <- fitme(destroyed ~ distance_to_nearest_tree * angular_diff_tree + area_of_trees_2m + 
                               area_ext_build_2 + distance_to_nearest_building + angular_diff_build +   mean_wind_sp + 
                               num_trees_200m + num_builds_200m + IMRF(1 | utm_x + utm_y, model = spde), data = Eaton_struc_scale)


eaton_struc_num200 <- fitme(destroyed ~ distance_to_nearest_tree * angular_diff_tree + area_of_trees_2m + 
                         area_ext_build_2 + distance_to_nearest_building + angular_diff_build +   mean_wind_sp + num_trees_200m + num_builds_200m + IMRF(1 | utm_x + utm_y, model = spde), data = Eaton_struc)

```


#plot

```{r}

plot_alt_models(eaton_struc_num200_scale)


```



# Kernel density bandwidth 500

```{r}

eaton_struc_tree_dens_500_scale <- fitme(destroyed ~ distance_to_nearest_tree * angular_diff_tree + area_of_trees_2m + 
                               area_ext_build_2 + distance_to_nearest_building + angular_diff_build +   mean_wind_sp + tree_dens_500 + build_dens +
                                IMRF(1 | utm_x + utm_y, model = spde), data = Eaton_struc_scale)


```

# plot

```{r}

plot_alt_models(eaton_struc_tree_dens_500_scale)

```


# Kernel density bandwidth 1000

```{r}

eaton_struc_tree_dens_1000_scale <- fitme(destroyed ~ distance_to_nearest_tree * angular_diff_tree + area_of_trees_2m + 
                               area_ext_build_2 + distance_to_nearest_building + angular_diff_build +   mean_wind_sp + tree_dens_1000 + build_dens +
                                IMRF(1 | utm_x + utm_y, model = spde), data = Eaton_struc_scale)


```

# plot

```{r}

plot_alt_models(eaton_struc_tree_dens_1000_scale)

```



# compare models



```{r}

mods <- list(eaton_struc_dens_scale, eaton_struc_area_scale, eaton_struc_num200_scale, eaton_struc_area50.100_scale, eaton_struc_tree_dens_500_scale, eaton_struc_tree_dens_1000_scale)

compare_AIC(models = mods)
```



